# -*- coding: utf-8 -*-
"""Task2_decision_tree_classification

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DJmjAAGwVri5c5xt3fWLdUY3Odq9pLbY

### Classification of IRIS dataset using Decision Tree Algorithm.

#### By: ABHIRAJ PILLAI
"""

# Importing libraries in Python
import sklearn.datasets as datasets
import pandas as pd

# Loading the iris dataset, as IRIS is a classic dataset, it has its own function to import IRIS dataset.
iris=datasets.load_iris()

# Forming the iris dataframe
X=pd.DataFrame(iris.data, columns=iris.feature_names)
print(X.head(5))
# Target is bascially all the labels i.e Setosa(0), Versicolor(1),Virginica(2)
y=iris.target
print(y)

"""### Now let us define the Decision Tree Algorithm"""

# Defining the decision tree algorithm
from sklearn.tree import DecisionTreeClassifier
dtree=DecisionTreeClassifier() #creating an object of DecisionTreeClassifier
dtree.fit(X,y)

print('Decision Tree Classifer Created')

"""### Visualising using pydotplus and displaying it using Image."""

# Install required libraries
!pip install pydotplus

# Import necessary libraries for graph viz
from sklearn.externals.six import StringIO  
from IPython.display import Image  
from sklearn.tree import export_graphviz
import pydotplus

# Visualize the graph
dot_data = StringIO() #Creating an object of StringIO which can support DOT File.
export_graphviz(dtree, out_file=dot_data, feature_names=iris.feature_names,  
                filled=True, rounded=True,
                special_characters=True)
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())  
Image(graph.create_png())